//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperSpace.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int IdSale { get; set; }
        public int IdUser { get; set; }
        public int IdPC { get; set; }
        public int IdTarif { get; set; }
        public System.DateTime TimeInSale { get; set; }
        public Nullable<System.DateTime> TimeOutSale { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual Tarif Tarif { get; set; }
        public virtual User User { get; set; }
    }
}
