//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfGapeev.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int IdAgent { get; set; }
        public string LastNameAgent { get; set; }
        public string FirstNameAgent { get; set; }
        public string MiddleNameAgent { get; set; }
        public decimal DealShareAgent { get; set; }
    }
}
